dist: trusty
addons:
  chrome: stable

language: python
python:
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-selenium
  - pip install chromedriver-installer
script:
  - pytest --driver=Chrome tests/
