dist: trusty
addons:
  chrome: stable

language: python
python:
  - "3.6"

install:
  - pip install pytest pytest-selenium chromedriver-installer
script:
  - pytest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
