dist: trusty

cache:
  directories:
  - .cache

addons:
  chrome: stable

language: python
python:
  - "3.6"

install:
  - pip install pytest pytest-selenium chromedriver-installer
script:
  - pytest -sv

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - grunt default # build js

after_failure:
  - 'for i in .log/*.html; do echo $i; cat "$i"; echo EOF; done'
  - 'for i in .log/assets/*.txt; do echo $i; cat "$i"; echo EOF; done'
  - 'for i in .log/assets/*.png; do echo $i; base64 "$i"; echo EOF; done'
